/*
Navicat MySQL Data Transfer

Source Server         : mysql
Source Server Version : 50726
Source Host           : localhost:3306
Source Database       : taller

Target Server Type    : MYSQL
Target Server Version : 50726
File Encoding         : 65001

Date: 2020-05-15 16:32:19
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for modelos
-- ----------------------------

-- ----------------------------
-- Records of modelos
-- ----------------------------
INSERT INTO `modelos` VALUES ('1', '1', 'QUATRO', '1', null, null);
INSERT INTO `modelos` VALUES ('2', '1', 'A4 QUATTRO', '1', null, null);
INSERT INTO `modelos` VALUES ('3', '2', '525 I', '1', null, null);
INSERT INTO `modelos` VALUES ('4', '2', '2002', '1', null, null);
INSERT INTO `modelos` VALUES ('5', '2', '320 I', '1', null, null);
INSERT INTO `modelos` VALUES ('6', '2', '535 I', '1', null, null);
INSERT INTO `modelos` VALUES ('7', '2', '325 I', '1', null, null);
INSERT INTO `modelos` VALUES ('8', '2', '528 I', '1', null, null);
INSERT INTO `modelos` VALUES ('9', '2', '328 I', '1', null, null);
INSERT INTO `modelos` VALUES ('10', '2', 'X5', '1', null, null);
INSERT INTO `modelos` VALUES ('11', '3', 'MONTECARLO', '1', null, null);
INSERT INTO `modelos` VALUES ('12', '3', 'S 10', '1', null, null);
INSERT INTO `modelos` VALUES ('13', '3', 'S-10', '1', null, null);
INSERT INTO `modelos` VALUES ('14', '3', 'PANEL C M V', '1', null, null);
INSERT INTO `modelos` VALUES ('15', '3', 'CELTA', '1', null, null);
INSERT INTO `modelos` VALUES ('16', '3', 'CMV', '1', null, null);
INSERT INTO `modelos` VALUES ('17', '3', 'METRO', '1', null, null);
INSERT INTO `modelos` VALUES ('18', '3', 'MONZA', '1', null, null);
INSERT INTO `modelos` VALUES ('19', '3', 'CORSA', '1', null, null);
INSERT INTO `modelos` VALUES ('20', '3', 'AVEO', '1', null, null);
INSERT INTO `modelos` VALUES ('21', '3', 'C M V', '1', null, null);
INSERT INTO `modelos` VALUES ('22', '3', 'BLAZER', '1', null, null);
INSERT INTO `modelos` VALUES ('23', '3', 'MALIBU', '1', null, null);
INSERT INTO `modelos` VALUES ('24', '3', 'CHEVY', '1', null, null);
INSERT INTO `modelos` VALUES ('25', '3', 'SPECTRUM', '1', null, null);
INSERT INTO `modelos` VALUES ('26', '3', 'C M P', '1', null, null);
INSERT INTO `modelos` VALUES ('27', '3', 'AVEO LS', '1', null, null);
INSERT INTO `modelos` VALUES ('28', '3', 'COLORADO', '1', null, null);
INSERT INTO `modelos` VALUES ('29', '4', 'P T CRUISER', '1', null, null);
INSERT INTO `modelos` VALUES ('30', '4', 'VOYAGER', '1', null, null);
INSERT INTO `modelos` VALUES ('31', '6', 'ATTIVO COACH', '1', null, null);
INSERT INTO `modelos` VALUES ('32', '6', 'ATIVO', '1', null, null);
INSERT INTO `modelos` VALUES ('33', '6', 'RACER GSI', '1', null, null);
INSERT INTO `modelos` VALUES ('34', '6', 'LABO', '1', null, null);
INSERT INTO `modelos` VALUES ('35', '6', 'FINO', '1', null, null);
INSERT INTO `modelos` VALUES ('36', '6', 'ATTIVO', '1', null, null);
INSERT INTO `modelos` VALUES ('37', '6', 'MATIZ', '1', null, null);
INSERT INTO `modelos` VALUES ('38', '6', 'MATIZ S', '1', null, null);
INSERT INTO `modelos` VALUES ('39', '7', 'CUORE', '1', null, null);
INSERT INTO `modelos` VALUES ('40', '7', 'CHARADE', '1', null, null);
INSERT INTO `modelos` VALUES ('41', '7', 'GRAN MOVE SE', '1', null, null);
INSERT INTO `modelos` VALUES ('42', '8', '120 Y', '1', null, null);
INSERT INTO `modelos` VALUES ('43', '9', 'RAM 1500', '1', null, null);
INSERT INTO `modelos` VALUES ('44', '9', 'NEON SXT', '1', null, null);
INSERT INTO `modelos` VALUES ('45', '9', 'CARAVAN', '1', null, null);
INSERT INTO `modelos` VALUES ('46', '9', 'CALIBER LXT', '1', null, null);
INSERT INTO `modelos` VALUES ('47', '9', 'RAM', '1', null, null);
INSERT INTO `modelos` VALUES ('48', '10', '40 HP', '1', null, null);
INSERT INTO `modelos` VALUES ('49', '10', 'INTRUDER', '1', null, null);
INSERT INTO `modelos` VALUES ('50', '11', '25', '1', null, null);
INSERT INTO `modelos` VALUES ('51', '12', 'ESCAPE', '1', null, null);
INSERT INTO `modelos` VALUES ('52', '12', 'FOCUS  ZX5', '1', null, null);
INSERT INTO `modelos` VALUES ('53', '12', 'ESCAPE XLS', '1', null, null);
INSERT INTO `modelos` VALUES ('54', '12', 'FOCUS', '1', null, null);
INSERT INTO `modelos` VALUES ('55', '12', 'RANGER', '1', null, null);
INSERT INTO `modelos` VALUES ('56', '12', 'EVEREST', '1', null, null);
INSERT INTO `modelos` VALUES ('57', '12', 'RANGER X L', '1', null, null);
INSERT INTO `modelos` VALUES ('58', '12', 'FOCUS  ZX 5', '1', null, null);
INSERT INTO `modelos` VALUES ('59', '12', 'RANGER LIMITED', '1', null, null);
INSERT INTO `modelos` VALUES ('60', '12', 'FOCUS ZX4', '1', null, null);
INSERT INTO `modelos` VALUES ('61', '12', 'RANGER X L T', '1', null, null);
INSERT INTO `modelos` VALUES ('62', '12', 'EXPLORER SPORT', '1', null, null);
INSERT INTO `modelos` VALUES ('63', '12', 'RANGER XLT', '1', null, null);
INSERT INTO `modelos` VALUES ('64', '12', 'FOCUS L X', '1', null, null);
INSERT INTO `modelos` VALUES ('65', '12', 'EXPLORER XLT', '1', null, null);
INSERT INTO `modelos` VALUES ('66', '12', 'RANGER  XL', '1', null, null);
INSERT INTO `modelos` VALUES ('67', '12', 'RANGER 4X4', '1', null, null);
INSERT INTO `modelos` VALUES ('68', '12', 'RANGER XL', '1', null, null);
INSERT INTO `modelos` VALUES ('69', '12', 'EVEREST XLT', '1', null, null);
INSERT INTO `modelos` VALUES ('70', '12', 'ESCORT SE', '1', null, null);
INSERT INTO `modelos` VALUES ('71', '12', 'MUSTANG', '1', null, null);
INSERT INTO `modelos` VALUES ('72', '12', 'EXPLORER', '1', null, null);
INSERT INTO `modelos` VALUES ('73', '12', 'ECOSPORT AMBI', '1', null, null);
INSERT INTO `modelos` VALUES ('74', '12', 'ECOSPORT XLS', '1', null, null);
INSERT INTO `modelos` VALUES ('75', '12', 'ESCAPE XLT', '1', null, null);
INSERT INTO `modelos` VALUES ('76', '12', 'EXPLORER SPOR', '1', null, null);
INSERT INTO `modelos` VALUES ('77', '13', 'CABEZAL', '1', null, null);
INSERT INTO `modelos` VALUES ('78', '14', 'METRO', '1', null, null);
INSERT INTO `modelos` VALUES ('79', '14', 'PRIZM', '1', null, null);
INSERT INTO `modelos` VALUES ('80', '14', 'TRACKER', '1', null, null);
INSERT INTO `modelos` VALUES ('81', '14', 'TRACKER SPORT', '1', null, null);
INSERT INTO `modelos` VALUES ('82', '15', 'C156', '1', null, null);
INSERT INTO `modelos` VALUES ('83', '17', 'CIVIC', '1', null, null);
INSERT INTO `modelos` VALUES ('84', '17', 'CR V 4X2', '1', null, null);
INSERT INTO `modelos` VALUES ('85', '17', 'CIVIC E X', '1', null, null);
INSERT INTO `modelos` VALUES ('86', '17', 'CRV LX', '1', null, null);
INSERT INTO `modelos` VALUES ('87', '17', 'ELEMENT', '1', null, null);
INSERT INTO `modelos` VALUES ('88', '17', 'CIVIC L X', '1', null, null);
INSERT INTO `modelos` VALUES ('89', '17', 'C R V', '1', null, null);
INSERT INTO `modelos` VALUES ('90', '17', 'CRV', '1', null, null);
INSERT INTO `modelos` VALUES ('91', '17', 'CIVIC LX', '1', null, null);
INSERT INTO `modelos` VALUES ('92', '17', 'ACCORD', '1', null, null);
INSERT INTO `modelos` VALUES ('93', '17', 'CRV  4WD', '1', null, null);
INSERT INTO `modelos` VALUES ('94', '17', 'CIVIC EX', '1', null, null);
INSERT INTO `modelos` VALUES ('95', '17', 'FIT', '1', null, null);
INSERT INTO `modelos` VALUES ('96', '17', 'CIVIC SI', '1', null, null);
INSERT INTO `modelos` VALUES ('97', '17', 'PILOT', '1', null, null);
INSERT INTO `modelos` VALUES ('98', '18', 'ELANTRA', '1', null, null);
INSERT INTO `modelos` VALUES ('99', '18', 'PANEL', '1', null, null);
INSERT INTO `modelos` VALUES ('100', '18', 'H-1', '1', null, null);
INSERT INTO `modelos` VALUES ('101', '18', 'GETZ GL', '1', null, null);
INSERT INTO `modelos` VALUES ('102', '18', 'ELANTRA GLS', '1', null, null);
INSERT INTO `modelos` VALUES ('103', '18', 'TIBURÓN', '1', null, null);
INSERT INTO `modelos` VALUES ('104', '18', 'ACCENT G L', '1', null, null);
INSERT INTO `modelos` VALUES ('105', '18', 'TIBURON', '1', null, null);
INSERT INTO `modelos` VALUES ('106', '18', 'ACCENT', '1', null, null);
INSERT INTO `modelos` VALUES ('107', '18', 'TUCSON', '1', null, null);
INSERT INTO `modelos` VALUES ('108', '18', 'H100', '1', null, null);
INSERT INTO `modelos` VALUES ('109', '18', 'H 1', '1', null, null);
INSERT INTO `modelos` VALUES ('110', '18', 'MATRIX GL', '1', null, null);
INSERT INTO `modelos` VALUES ('111', '18', 'H-100', '1', null, null);
INSERT INTO `modelos` VALUES ('112', '19', 'SCHOOL BUS', '1', null, null);
INSERT INTO `modelos` VALUES ('113', '20', 'RODEO', '1', null, null);
INSERT INTO `modelos` VALUES ('114', '20', 'PUP', '1', null, null);
INSERT INTO `modelos` VALUES ('115', '20', 'D MAX', '1', null, null);
INSERT INTO `modelos` VALUES ('116', '20', 'TFR', '1', null, null);
INSERT INTO `modelos` VALUES ('117', '20', 'PICK UP', '1', null, null);
INSERT INTO `modelos` VALUES ('118', '20', 'FSR33L-02', '1', null, null);
INSERT INTO `modelos` VALUES ('119', '20', 'NMR', '1', null, null);
INSERT INTO `modelos` VALUES ('120', '20', '4X4', '1', null, null);
INSERT INTO `modelos` VALUES ('121', '20', 'NPR', '1', null, null);
INSERT INTO `modelos` VALUES ('122', '20', 'NQR', '1', null, null);
INSERT INTO `modelos` VALUES ('123', '21', 'CHEROKEE', '1', null, null);
INSERT INTO `modelos` VALUES ('124', '21', 'CHEROKEE SPORT', '1', null, null);
INSERT INTO `modelos` VALUES ('125', '21', 'LIBERTY LTD', '1', null, null);
INSERT INTO `modelos` VALUES ('126', '21', 'GRAND CHEROKEE', '1', null, null);
INSERT INTO `modelos` VALUES ('127', '21', 'PATRIOT', '1', null, null);
INSERT INTO `modelos` VALUES ('128', '21', 'GRAND CHEROOKE', '1', null, null);
INSERT INTO `modelos` VALUES ('129', '21', 'LIBERTY', '1', null, null);
INSERT INTO `modelos` VALUES ('130', '21', 'WRANGLER', '1', null, null);
INSERT INTO `modelos` VALUES ('131', '21', 'COMPASS', '1', null, null);
INSERT INTO `modelos` VALUES ('132', '22', '6 H P', '1', null, null);
INSERT INTO `modelos` VALUES ('133', '23', '3.3 HP', '1', null, null);
INSERT INTO `modelos` VALUES ('134', '24', 'K 2700', '1', null, null);
INSERT INTO `modelos` VALUES ('135', '24', 'RIO R S', '1', null, null);
INSERT INTO `modelos` VALUES ('136', '24', 'SPORTAGE  EX', '1', null, null);
INSERT INTO `modelos` VALUES ('137', '24', 'CARENS', '1', null, null);
INSERT INTO `modelos` VALUES ('138', '24', 'OPTIMA L X', '1', null, null);
INSERT INTO `modelos` VALUES ('139', '24', 'TOWNER', '1', null, null);
INSERT INTO `modelos` VALUES ('140', '24', 'SEDONA E X', '1', null, null);
INSERT INTO `modelos` VALUES ('141', '24', 'CARNIVAL GS', '1', null, null);
INSERT INTO `modelos` VALUES ('142', '24', 'OPTIMA', '1', null, null);
INSERT INTO `modelos` VALUES ('143', '24', 'RIO', '1', null, null);
INSERT INTO `modelos` VALUES ('144', '24', 'SPORTAGE', '1', null, null);
INSERT INTO `modelos` VALUES ('145', '24', 'RIO E X', '1', null, null);
INSERT INTO `modelos` VALUES ('146', '24', 'SEPHIA', '1', null, null);
INSERT INTO `modelos` VALUES ('147', '24', 'SPECTRA EX', '1', null, null);
INSERT INTO `modelos` VALUES ('148', '24', 'K2700', '1', null, null);
INSERT INTO `modelos` VALUES ('149', '24', 'SPECTRA', '1', null, null);
INSERT INTO `modelos` VALUES ('150', '24', 'SPORTAGE LX', '1', null, null);
INSERT INTO `modelos` VALUES ('151', '24', 'SORENTO LX', '1', null, null);
INSERT INTO `modelos` VALUES ('152', '24', 'RIO LX', '1', null, null);
INSERT INTO `modelos` VALUES ('153', '24', 'ESPECTRA', '1', null, null);
INSERT INTO `modelos` VALUES ('154', '24', 'FORTE', '1', null, null);
INSERT INTO `modelos` VALUES ('155', '24', 'PICANTO', '1', null, null);
INSERT INTO `modelos` VALUES ('156', '24', 'RIO EX', '1', null, null);
INSERT INTO `modelos` VALUES ('157', '24', 'SPORTAGE EX', '1', null, null);
INSERT INTO `modelos` VALUES ('158', '24', 'SPORTGE LX', '1', null, null);
INSERT INTO `modelos` VALUES ('159', '24', 'K3600', '1', null, null);
INSERT INTO `modelos` VALUES ('160', '24', 'SOUL', '1', null, null);
INSERT INTO `modelos` VALUES ('161', '25', 'VESPA', '1', null, null);
INSERT INTO `modelos` VALUES ('162', '26', 'DEPORTIVO', '1', null, null);
INSERT INTO `modelos` VALUES ('163', '27', 'LR2 SE', '1', null, null);
INSERT INTO `modelos` VALUES ('164', '27', 'RANGE ROVER', '1', null, null);
INSERT INTO `modelos` VALUES ('165', '27', 'RANGE ROVER SPORT', '1', null, null);
INSERT INTO `modelos` VALUES ('166', '28', 'RX 300', '1', null, null);
INSERT INTO `modelos` VALUES ('167', '28', 'IS 250', '1', null, null);
INSERT INTO `modelos` VALUES ('168', '28', 'GX 470', '1', null, null);
INSERT INTO `modelos` VALUES ('169', '30', 'BT-50 HI', '1', null, null);
INSERT INTO `modelos` VALUES ('170', '30', 'E2200', '1', null, null);
INSERT INTO `modelos` VALUES ('171', '30', 'PROTEGE 5', '1', null, null);
INSERT INTO `modelos` VALUES ('172', '30', 'PROTEGE', '1', null, null);
INSERT INTO `modelos` VALUES ('173', '30', 'TRIBUTE', '1', null, null);
INSERT INTO `modelos` VALUES ('174', '30', '6 R', '1', null, null);
INSERT INTO `modelos` VALUES ('175', '30', '626', '1', null, null);
INSERT INTO `modelos` VALUES ('176', '30', '323', '1', null, null);
INSERT INTO `modelos` VALUES ('177', '30', '3', '1', null, null);
INSERT INTO `modelos` VALUES ('178', '30', '323 LX', '1', null, null);
INSERT INTO `modelos` VALUES ('179', '30', 'PROTEGE  L X', '1', null, null);
INSERT INTO `modelos` VALUES ('180', '30', 'B 2900', '1', null, null);
INSERT INTO `modelos` VALUES ('181', '30', '6', '1', null, null);
INSERT INTO `modelos` VALUES ('182', '30', '323 L X', '1', null, null);
INSERT INTO `modelos` VALUES ('183', '30', 'BT 50', '1', null, null);
INSERT INTO `modelos` VALUES ('184', '30', 'B2500', '1', null, null);
INSERT INTO `modelos` VALUES ('185', '30', '3 V', '1', null, null);
INSERT INTO `modelos` VALUES ('186', '30', 'B 2300', '1', null, null);
INSERT INTO `modelos` VALUES ('187', '30', '3000', '1', null, null);
INSERT INTO `modelos` VALUES ('188', '30', '626 GLX', '1', null, null);
INSERT INTO `modelos` VALUES ('189', '30', '6', '1', null, null);
INSERT INTO `modelos` VALUES ('190', '30', 'CX 7', '1', null, null);
INSERT INTO `modelos` VALUES ('191', '30', '6 V', '1', null, null);
INSERT INTO `modelos` VALUES ('192', '30', 'B2300', '1', null, null);
INSERT INTO `modelos` VALUES ('193', '30', '3V', '1', null, null);
INSERT INTO `modelos` VALUES ('194', '30', 'PROTEGE ES', '1', null, null);
INSERT INTO `modelos` VALUES ('195', '30', '323 GLX', '1', null, null);
INSERT INTO `modelos` VALUES ('196', '30', '3 SHREWSBURY', '1', null, null);
INSERT INTO `modelos` VALUES ('197', '31', '300', '1', null, null);
INSERT INTO `modelos` VALUES ('198', '31', 'E 240', '1', null, null);
INSERT INTO `modelos` VALUES ('199', '31', 'ML 320', '1', null, null);
INSERT INTO `modelos` VALUES ('200', '31', '250', '1', null, null);
INSERT INTO `modelos` VALUES ('201', '32', 'MARINO', '1', null, null);
INSERT INTO `modelos` VALUES ('202', '33', 'COOPER S', '1', null, null);
INSERT INTO `modelos` VALUES ('203', '34', 'L-200', '1', null, null);
INSERT INTO `modelos` VALUES ('204', '34', 'OUTLANDER', '1', null, null);
INSERT INTO `modelos` VALUES ('205', '34', 'MIRAGE', '1', null, null);
INSERT INTO `modelos` VALUES ('206', '34', 'LANCER G L', '1', null, null);
INSERT INTO `modelos` VALUES ('207', '34', 'MONTERO  I O', '1', null, null);
INSERT INTO `modelos` VALUES ('208', '34', 'L 300', '1', null, null);
INSERT INTO `modelos` VALUES ('209', '34', 'L 200', '1', null, null);
INSERT INTO `modelos` VALUES ('210', '34', 'NATIVA', '1', null, null);
INSERT INTO `modelos` VALUES ('211', '34', 'ECLIPSE', '1', null, null);
INSERT INTO `modelos` VALUES ('212', '34', 'LANCER', '1', null, null);
INSERT INTO `modelos` VALUES ('213', '34', 'LANCER GL', '1', null, null);
INSERT INTO `modelos` VALUES ('214', '34', 'LANCER ES', '1', null, null);
INSERT INTO `modelos` VALUES ('215', '34', 'LANCER GLX', '1', null, null);
INSERT INTO `modelos` VALUES ('216', '34', 'CANTER', '1', null, null);
INSERT INTO `modelos` VALUES ('217', '34', 'L300', '1', null, null);
INSERT INTO `modelos` VALUES ('218', '34', 'GALANT', '1', null, null);
INSERT INTO `modelos` VALUES ('219', '34', 'L200', '1', null, null);
INSERT INTO `modelos` VALUES ('220', '34', 'MONTERO', '1', null, null);
INSERT INTO `modelos` VALUES ('221', '34', 'PICK UP L 200', '1', null, null);
INSERT INTO `modelos` VALUES ('222', '34', 'LANCER EX', '1', null, null);
INSERT INTO `modelos` VALUES ('223', '34', 'OUTLANDER  ASX', '1', null, null);
INSERT INTO `modelos` VALUES ('224', '34', 'MONTERO GLS', '1', null, null);
INSERT INTO `modelos` VALUES ('225', '34', 'MONTERO IO', '1', null, null);
INSERT INTO `modelos` VALUES ('226', '34', 'MONTERO GL X', '1', null, null);
INSERT INTO `modelos` VALUES ('227', '34', 'ASX', '1', null, null);
INSERT INTO `modelos` VALUES ('228', '35', 'NAVARA SE', '1', null, null);
INSERT INTO `modelos` VALUES ('229', '35', 'FRONTIER', '1', null, null);
INSERT INTO `modelos` VALUES ('230', '35', 'SENTRA', '1', null, null);
INSERT INTO `modelos` VALUES ('231', '35', 'PATHFINDER', '1', null, null);
INSERT INTO `modelos` VALUES ('232', '35', 'Z24', '1', null, null);
INSERT INTO `modelos` VALUES ('233', '35', 'PICK UP', '1', null, null);
INSERT INTO `modelos` VALUES ('234', '35', 'SUNNY', '1', null, null);
INSERT INTO `modelos` VALUES ('235', '35', 'PLATINA', '1', null, null);
INSERT INTO `modelos` VALUES ('236', '35', 'ALMERA', '1', null, null);
INSERT INTO `modelos` VALUES ('237', '35', 'SENTRA 1.8', '1', null, null);
INSERT INTO `modelos` VALUES ('238', '35', 'SENTRA  GXE', '1', null, null);
INSERT INTO `modelos` VALUES ('239', '35', 'NAVARA', '1', null, null);
INSERT INTO `modelos` VALUES ('240', '35', 'PATROL', '1', null, null);
INSERT INTO `modelos` VALUES ('241', '35', 'ALTIMA', '1', null, null);
INSERT INTO `modelos` VALUES ('242', '35', 'PATROL S G L', '1', null, null);
INSERT INTO `modelos` VALUES ('243', '35', 'PICK UP D 21', '1', null, null);
INSERT INTO `modelos` VALUES ('244', '35', 'TIIDA  SE', '1', null, null);
INSERT INTO `modelos` VALUES ('245', '35', 'FRONTIER LCV', '1', null, null);
INSERT INTO `modelos` VALUES ('246', '35', 'D 21', '1', null, null);
INSERT INTO `modelos` VALUES ('247', '35', 'MURANO', '1', null, null);
INSERT INTO `modelos` VALUES ('248', '35', 'D21', '1', null, null);
INSERT INTO `modelos` VALUES ('249', '35', 'SENTRA S', '1', null, null);
INSERT INTO `modelos` VALUES ('250', '35', '200 SX', '1', null, null);
INSERT INTO `modelos` VALUES ('251', '35', 'SENTRA SR', '1', null, null);
INSERT INTO `modelos` VALUES ('252', '35', 'SENTRA GXE', '1', null, null);
INSERT INTO `modelos` VALUES ('253', '35', '4X4', '1', null, null);
INSERT INTO `modelos` VALUES ('254', '35', 'MARCH', '1', null, null);
INSERT INTO `modelos` VALUES ('255', '35', 'VERSA SL', '1', null, null);
INSERT INTO `modelos` VALUES ('256', '35', 'X TRAIL SE', '1', null, null);
INSERT INTO `modelos` VALUES ('257', '35', 'NAVARA LE', '1', null, null);
INSERT INTO `modelos` VALUES ('258', '35', 'TIIDA', '1', null, null);
INSERT INTO `modelos` VALUES ('259', '35', 'ROGUE', '1', null, null);
INSERT INTO `modelos` VALUES ('260', '35', 'VANETTE', '1', null, null);
INSERT INTO `modelos` VALUES ('261', '35', 'FRONTIER AX', '1', null, null);
INSERT INTO `modelos` VALUES ('262', '35', 'AD', '1', null, null);
INSERT INTO `modelos` VALUES ('263', '35', 'N/D', '1', null, null);
INSERT INTO `modelos` VALUES ('264', '35', 'VERSA', '1', null, null);
INSERT INTO `modelos` VALUES ('265', '35', 'JUKE', '1', null, null);
INSERT INTO `modelos` VALUES ('266', '36', 'PARTNER', '1', null, null);
INSERT INTO `modelos` VALUES ('267', '36', '206 X R', '1', null, null);
INSERT INTO `modelos` VALUES ('268', '36', '206 XR', '1', null, null);
INSERT INTO `modelos` VALUES ('269', '36', '206', '1', null, null);
INSERT INTO `modelos` VALUES ('270', '36', '206 XRPR  HDI', '1', null, null);
INSERT INTO `modelos` VALUES ('271', '36', '307 XR', '1', null, null);
INSERT INTO `modelos` VALUES ('272', '36', '207 SPORT 1.6', '1', null, null);
INSERT INTO `modelos` VALUES ('273', '36', '405', '1', null, null);
INSERT INTO `modelos` VALUES ('274', '36', '406 ST', '1', null, null);
INSERT INTO `modelos` VALUES ('275', '37', 'VIBE', '1', null, null);
INSERT INTO `modelos` VALUES ('276', '38', 'SCENIC', '1', null, null);
INSERT INTO `modelos` VALUES ('277', '38', 'CLIO', '1', null, null);
INSERT INTO `modelos` VALUES ('278', '41', 'TC', '1', null, null);
INSERT INTO `modelos` VALUES ('279', '41', 'XB', '1', null, null);
INSERT INTO `modelos` VALUES ('280', '42', 'CORDOBA', '1', null, null);
INSERT INTO `modelos` VALUES ('281', '44', 'FORTWO', '1', null, null);
INSERT INTO `modelos` VALUES ('282', '45', 'KYRON M200', '1', null, null);
INSERT INTO `modelos` VALUES ('283', '45', 'REXTON RX290', '1', null, null);
INSERT INTO `modelos` VALUES ('284', '46', 'LEGACY', '1', null, null);
INSERT INTO `modelos` VALUES ('285', '47', 'JIMMY', '1', null, null);
INSERT INTO `modelos` VALUES ('286', '47', 'STEEM', '1', null, null);
INSERT INTO `modelos` VALUES ('287', '47', 'GRAND VITARA', '1', null, null);
INSERT INTO `modelos` VALUES ('288', '47', 'FORENZA', '1', null, null);
INSERT INTO `modelos` VALUES ('289', '47', 'A X 100', '1', null, null);
INSERT INTO `modelos` VALUES ('291', '47', ' AX 100', '1', null, null);
INSERT INTO `modelos` VALUES ('292', '47', 'ESTEEM', '1', null, null);
INSERT INTO `modelos` VALUES ('293', '47', 'AEREO SX', '1', null, null);
INSERT INTO `modelos` VALUES ('294', '47', 'SAMURAI', '1', null, null);
INSERT INTO `modelos` VALUES ('295', '47', 'APV', '1', null, null);
INSERT INTO `modelos` VALUES ('296', '47', 'XL 7', '1', null, null);
INSERT INTO `modelos` VALUES ('297', '47', 'GN 125 F', '1', null, null);
INSERT INTO `modelos` VALUES ('298', '47', 'SX 4', '1', null, null);
INSERT INTO `modelos` VALUES ('299', '47', 'GN 125 H', '1', null, null);
INSERT INTO `modelos` VALUES ('300', '47', 'GN 125H', '1', null, null);
INSERT INTO `modelos` VALUES ('301', '48', 'SPORT', '1', null, null);
INSERT INTO `modelos` VALUES ('302', '49', 'COROLLA', '1', null, null);
INSERT INTO `modelos` VALUES ('303', '49', 'TERCEL', '1', null, null);
INSERT INTO `modelos` VALUES ('304', '49', 'ECHO', '1', null, null);
INSERT INTO `modelos` VALUES ('305', '49', 'YARIS', '1', null, null);
INSERT INTO `modelos` VALUES ('306', '49', 'STARLET', '1', null, null);
INSERT INTO `modelos` VALUES ('307', '49', 'COROLLA TERCEL', '1', null, null);
INSERT INTO `modelos` VALUES ('308', '49', 'HI ACE', '1', null, null);
INSERT INTO `modelos` VALUES ('309', '49', 'CORONA', '1', null, null);
INSERT INTO `modelos` VALUES ('310', '49', 'COROLLA CE', '1', null, null);
INSERT INTO `modelos` VALUES ('311', '49', 'COROLLA SE', '1', null, null);
INSERT INTO `modelos` VALUES ('312', '49', 'RAV 4X4', '1', null, null);
INSERT INTO `modelos` VALUES ('313', '49', 'HILUX', '1', null, null);
INSERT INTO `modelos` VALUES ('314', '49', 'CORONA GL', '1', null, null);
INSERT INTO `modelos` VALUES ('315', '49', 'COROLLA XLI', '1', null, null);
INSERT INTO `modelos` VALUES ('316', '49', 'LAND CRUISER', '1', null, null);
INSERT INTO `modelos` VALUES ('317', '49', 'MATRIX', '1', null, null);
INSERT INTO `modelos` VALUES ('318', '49', 'COROLLA GLI', '1', null, null);
INSERT INTO `modelos` VALUES ('319', '49', 'LITEACE', '1', null, null);
INSERT INTO `modelos` VALUES ('320', '49', 'HI LUX', '1', null, null);
INSERT INTO `modelos` VALUES ('321', '49', 'FOUR RUNNER SR5', '1', null, null);
INSERT INTO `modelos` VALUES ('322', '49', 'TACOMA', '1', null, null);
INSERT INTO `modelos` VALUES ('323', '49', 'FOUR RUNNER', '1', null, null);
INSERT INTO `modelos` VALUES ('324', '49', 'RAV 4', '1', null, null);
INSERT INTO `modelos` VALUES ('325', '49', 'RAV 4 XLE', '1', null, null);
INSERT INTO `modelos` VALUES ('326', '49', 'FORTUNER', '1', null, null);
INSERT INTO `modelos` VALUES ('327', '49', 'LAND CRUSIER PRADO', '1', null, null);
INSERT INTO `modelos` VALUES ('328', '49', 'DYNA', '1', null, null);
INSERT INTO `modelos` VALUES ('329', '49', 'SCION', '1', null, null);
INSERT INTO `modelos` VALUES ('330', '49', 'SCION XB', '1', null, null);
INSERT INTO `modelos` VALUES ('331', '52', 'FOX 1.6', '1', null, null);
INSERT INTO `modelos` VALUES ('332', '52', 'SAVEIRO', '1', null, null);
INSERT INTO `modelos` VALUES ('333', '52', 'POLO COMFORT L', '1', null, null);
INSERT INTO `modelos` VALUES ('334', '52', 'GOLF', '1', null, null);
INSERT INTO `modelos` VALUES ('335', '52', 'JETTA EUROPA', '1', null, null);
INSERT INTO `modelos` VALUES ('336', '52', '113-1500', '1', null, null);
INSERT INTO `modelos` VALUES ('337', '52', 'TIGUAN', '1', null, null);
INSERT INTO `modelos` VALUES ('338', '52', 'KEFER', '1', null, null);
INSERT INTO `modelos` VALUES ('339', '52', 'PARATI', '1', null, null);
INSERT INTO `modelos` VALUES ('340', '52', 'GOL', '1', null, null);
INSERT INTO `modelos` VALUES ('341', '52', 'BEETLE', '1', null, null);
INSERT INTO `modelos` VALUES ('342', '52', 'COMBI', '1', null, null);
INSERT INTO `modelos` VALUES ('343', '52', 'JETTA', '1', null, null);
INSERT INTO `modelos` VALUES ('344', '52', 'ESCARABAJO', '1', null, null);
INSERT INTO `modelos` VALUES ('345', '52', 'JETTA GL 2.0', '1', null, null);
INSERT INTO `modelos` VALUES ('346', '52', 'GOLF VARIANT', '1', null, null);
INSERT INTO `modelos` VALUES ('347', '54', '245', '1', null, null);
INSERT INTO `modelos` VALUES ('348', '54', 'S 60', '1', null, null);
INSERT INTO `modelos` VALUES ('349', '54', 'S 70', '1', null, null);
INSERT INTO `modelos` VALUES ('350', '54', 'C 30  T5', '1', null, null);
INSERT INTO `modelos` VALUES ('351', '56', 'GTP30TK', '1', null, null);
INSERT INTO `modelos` VALUES ('352', '57', 'YD 110 S', '1', null, null);
INSERT INTO `modelos` VALUES ('353', '57', '750 SS', '1', null, null);
INSERT INTO `modelos` VALUES ('354', '57', 'YFM 350 FWA', '1', null, null);
INSERT INTO `modelos` VALUES ('355', '57', '250 HP', '1', null, null);
INSERT INTO `modelos` VALUES ('356', '57', 'YBR 125', '1', null, null);
INSERT INTO `modelos` VALUES ('357', '57', 'OUTBOARD', '1', null, null);
INSERT INTO `modelos` VALUES ('358', '3', 'AVEEO 5 LT', '1', null, null);
INSERT INTO `modelos` VALUES ('359', '55', 'Jetta', '1', '2020-04-07 09:50:08', '2020-04-07 09:50:08');
SET FOREIGN_KEY_CHECKS=1;
